image: node:16

before_script:
  - apt-get update
  - apt-get install zip

cache:
  paths:
    - node_modules/

stages:
  - init
  - build

############### BETA ################

build-prod:
  stage: build
  script:
    - export
    - npm ci
    - npm run build
    - node update-build-tags.js --branch=$CI_COMMIT_BRANCH --gitlabpath=$CI_PROJECT_PATH --jobname=$CI_JOB_NAME  --tag=$CI_COMMIT_TAG --bucket=$S3_BUCKET
    - cp ./dist/system.json ./system.json
    - mv dist my-system
    - zip -q my-system.zip -r my-system
  artifacts:
    paths:
      - my-system.zip
      - system.json
  only:
    # Examples: 0.1.0
    # At least one digit + period, followed by additional digits, followed by an optional beta/alpha, followed by a build number.
    - /^(\d+\.)+(\d+)*((beta|alpha)+(-)*\d+)*$/i
  except:
    - branches